### ISSUE TITLE
AttributeError: module 'fullsubnet_plus.model.fullsubnet_plus' has no attribute 'Sub_FullSubNet_Plus'

### ISSUE THREAD

**Issue by liziru** [hit-thusz-RookieCJ/FullSubNet-plus#6]
你好，谢谢你的工作。
我尝试训练遇到以下问题：
`-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/lee/Documents/software/anaconda3/envs/fsnetplus/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/lee/Desktop/workspace/project/se/ns/tests/FullSubNet-plus/speech_enhance/tools/train.py", line 58, in entry
    model = initialize_module(config["model"]["path"], args=config["model"]["args"])
  File "/home/lee/Desktop/workspace/project/se/ns/tests/FullSubNet-plus/speech_enhance/audio_zen/utils.py", line 91, in initialize_module
    class_or_function = getattr(module, class_or_function_name)
AttributeError: module 'fullsubnet_plus.model.fullsubnet_plus' has no attribute 'Sub_FullSubNet_Plus'` 

我在工程中全局搜索没有找到这个函数或文件，请问该如何解决？

**Comment by hit-thusz-RookieCJ** [comment]
你好，不好意思，我在train.toml里的模型的地址写错了，现已纠正并更新参考！谢谢指正

**Comment by hit-thusz-RookieCJ** [comment]
你好，不好意思，我在train.toml里的模型的地址写错了，现已纠正并更新仓库！谢谢指正！
